# Generated by Django 2.2 on 2020-03-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
